// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/scraper/scraper.proto

package scraper

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckStoryURLRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckStoryURLRequest) Reset()         { *m = CheckStoryURLRequest{} }
func (m *CheckStoryURLRequest) String() string { return proto.CompactTextString(m) }
func (*CheckStoryURLRequest) ProtoMessage()    {}
func (*CheckStoryURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_scraper_0a6b167aa046985f, []int{0}
}
func (m *CheckStoryURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckStoryURLRequest.Unmarshal(m, b)
}
func (m *CheckStoryURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckStoryURLRequest.Marshal(b, m, deterministic)
}
func (dst *CheckStoryURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckStoryURLRequest.Merge(dst, src)
}
func (m *CheckStoryURLRequest) XXX_Size() int {
	return xxx_messageInfo_CheckStoryURLRequest.Size(m)
}
func (m *CheckStoryURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckStoryURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckStoryURLRequest proto.InternalMessageInfo

func (m *CheckStoryURLRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CheckStoryURLResponse struct {
	Allowed              bool     `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckStoryURLResponse) Reset()         { *m = CheckStoryURLResponse{} }
func (m *CheckStoryURLResponse) String() string { return proto.CompactTextString(m) }
func (*CheckStoryURLResponse) ProtoMessage()    {}
func (*CheckStoryURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_scraper_0a6b167aa046985f, []int{1}
}
func (m *CheckStoryURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckStoryURLResponse.Unmarshal(m, b)
}
func (m *CheckStoryURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckStoryURLResponse.Marshal(b, m, deterministic)
}
func (dst *CheckStoryURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckStoryURLResponse.Merge(dst, src)
}
func (m *CheckStoryURLResponse) XXX_Size() int {
	return xxx_messageInfo_CheckStoryURLResponse.Size(m)
}
func (m *CheckStoryURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckStoryURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckStoryURLResponse proto.InternalMessageInfo

func (m *CheckStoryURLResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

type FetchStoryMetadataRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchStoryMetadataRequest) Reset()         { *m = FetchStoryMetadataRequest{} }
func (m *FetchStoryMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*FetchStoryMetadataRequest) ProtoMessage()    {}
func (*FetchStoryMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_scraper_0a6b167aa046985f, []int{2}
}
func (m *FetchStoryMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchStoryMetadataRequest.Unmarshal(m, b)
}
func (m *FetchStoryMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchStoryMetadataRequest.Marshal(b, m, deterministic)
}
func (dst *FetchStoryMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchStoryMetadataRequest.Merge(dst, src)
}
func (m *FetchStoryMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_FetchStoryMetadataRequest.Size(m)
}
func (m *FetchStoryMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchStoryMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchStoryMetadataRequest proto.InternalMessageInfo

func (m *FetchStoryMetadataRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type FetchStoryMetadataResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	NumChapters          int32    `protobuf:"varint,4,opt,name=numChapters,proto3" json:"numChapters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchStoryMetadataResponse) Reset()         { *m = FetchStoryMetadataResponse{} }
func (m *FetchStoryMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*FetchStoryMetadataResponse) ProtoMessage()    {}
func (*FetchStoryMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_scraper_0a6b167aa046985f, []int{3}
}
func (m *FetchStoryMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchStoryMetadataResponse.Unmarshal(m, b)
}
func (m *FetchStoryMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchStoryMetadataResponse.Marshal(b, m, deterministic)
}
func (dst *FetchStoryMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchStoryMetadataResponse.Merge(dst, src)
}
func (m *FetchStoryMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_FetchStoryMetadataResponse.Size(m)
}
func (m *FetchStoryMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchStoryMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchStoryMetadataResponse proto.InternalMessageInfo

func (m *FetchStoryMetadataResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *FetchStoryMetadataResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *FetchStoryMetadataResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *FetchStoryMetadataResponse) GetNumChapters() int32 {
	if m != nil {
		return m.NumChapters
	}
	return 0
}

type FetchChapterRequest struct {
	StoryUrl             string   `protobuf:"bytes,1,opt,name=storyUrl,proto3" json:"storyUrl,omitempty"`
	ChapterIndex         int32    `protobuf:"varint,2,opt,name=chapterIndex,proto3" json:"chapterIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchChapterRequest) Reset()         { *m = FetchChapterRequest{} }
func (m *FetchChapterRequest) String() string { return proto.CompactTextString(m) }
func (*FetchChapterRequest) ProtoMessage()    {}
func (*FetchChapterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_scraper_0a6b167aa046985f, []int{4}
}
func (m *FetchChapterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchChapterRequest.Unmarshal(m, b)
}
func (m *FetchChapterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchChapterRequest.Marshal(b, m, deterministic)
}
func (dst *FetchChapterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchChapterRequest.Merge(dst, src)
}
func (m *FetchChapterRequest) XXX_Size() int {
	return xxx_messageInfo_FetchChapterRequest.Size(m)
}
func (m *FetchChapterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchChapterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchChapterRequest proto.InternalMessageInfo

func (m *FetchChapterRequest) GetStoryUrl() string {
	if m != nil {
		return m.StoryUrl
	}
	return ""
}

func (m *FetchChapterRequest) GetChapterIndex() int32 {
	if m != nil {
		return m.ChapterIndex
	}
	return 0
}

type FetchChapterResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Html                 string   `protobuf:"bytes,3,opt,name=html,proto3" json:"html,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchChapterResponse) Reset()         { *m = FetchChapterResponse{} }
func (m *FetchChapterResponse) String() string { return proto.CompactTextString(m) }
func (*FetchChapterResponse) ProtoMessage()    {}
func (*FetchChapterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_scraper_0a6b167aa046985f, []int{5}
}
func (m *FetchChapterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchChapterResponse.Unmarshal(m, b)
}
func (m *FetchChapterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchChapterResponse.Marshal(b, m, deterministic)
}
func (dst *FetchChapterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchChapterResponse.Merge(dst, src)
}
func (m *FetchChapterResponse) XXX_Size() int {
	return xxx_messageInfo_FetchChapterResponse.Size(m)
}
func (m *FetchChapterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchChapterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchChapterResponse proto.InternalMessageInfo

func (m *FetchChapterResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *FetchChapterResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *FetchChapterResponse) GetHtml() string {
	if m != nil {
		return m.Html
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckStoryURLRequest)(nil), "scraper.CheckStoryURLRequest")
	proto.RegisterType((*CheckStoryURLResponse)(nil), "scraper.CheckStoryURLResponse")
	proto.RegisterType((*FetchStoryMetadataRequest)(nil), "scraper.FetchStoryMetadataRequest")
	proto.RegisterType((*FetchStoryMetadataResponse)(nil), "scraper.FetchStoryMetadataResponse")
	proto.RegisterType((*FetchChapterRequest)(nil), "scraper.FetchChapterRequest")
	proto.RegisterType((*FetchChapterResponse)(nil), "scraper.FetchChapterResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ScraperClient is the client API for Scraper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScraperClient interface {
	// CheckStoryURL returns true if the specified URL matches the expected
	// pattern of a story supported by this service
	CheckStoryURL(ctx context.Context, in *CheckStoryURLRequest, opts ...grpc.CallOption) (*CheckStoryURLResponse, error)
	// FetchStoryMetadata fetches the title, author, and chapter index of a story,
	// but not the actual chapter text
	FetchStoryMetadata(ctx context.Context, in *FetchStoryMetadataRequest, opts ...grpc.CallOption) (*FetchStoryMetadataResponse, error)
	// FetchChapter fetches one chapter of a story
	FetchChapter(ctx context.Context, in *FetchChapterRequest, opts ...grpc.CallOption) (*FetchChapterResponse, error)
}

type scraperClient struct {
	cc *grpc.ClientConn
}

func NewScraperClient(cc *grpc.ClientConn) ScraperClient {
	return &scraperClient{cc}
}

func (c *scraperClient) CheckStoryURL(ctx context.Context, in *CheckStoryURLRequest, opts ...grpc.CallOption) (*CheckStoryURLResponse, error) {
	out := new(CheckStoryURLResponse)
	err := c.cc.Invoke(ctx, "/scraper.Scraper/CheckStoryURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperClient) FetchStoryMetadata(ctx context.Context, in *FetchStoryMetadataRequest, opts ...grpc.CallOption) (*FetchStoryMetadataResponse, error) {
	out := new(FetchStoryMetadataResponse)
	err := c.cc.Invoke(ctx, "/scraper.Scraper/FetchStoryMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperClient) FetchChapter(ctx context.Context, in *FetchChapterRequest, opts ...grpc.CallOption) (*FetchChapterResponse, error) {
	out := new(FetchChapterResponse)
	err := c.cc.Invoke(ctx, "/scraper.Scraper/FetchChapter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScraperServer is the server API for Scraper service.
type ScraperServer interface {
	// CheckStoryURL returns true if the specified URL matches the expected
	// pattern of a story supported by this service
	CheckStoryURL(context.Context, *CheckStoryURLRequest) (*CheckStoryURLResponse, error)
	// FetchStoryMetadata fetches the title, author, and chapter index of a story,
	// but not the actual chapter text
	FetchStoryMetadata(context.Context, *FetchStoryMetadataRequest) (*FetchStoryMetadataResponse, error)
	// FetchChapter fetches one chapter of a story
	FetchChapter(context.Context, *FetchChapterRequest) (*FetchChapterResponse, error)
}

func RegisterScraperServer(s *grpc.Server, srv ScraperServer) {
	s.RegisterService(&_Scraper_serviceDesc, srv)
}

func _Scraper_CheckStoryURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStoryURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServer).CheckStoryURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraper.Scraper/CheckStoryURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServer).CheckStoryURL(ctx, req.(*CheckStoryURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scraper_FetchStoryMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchStoryMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServer).FetchStoryMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraper.Scraper/FetchStoryMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServer).FetchStoryMetadata(ctx, req.(*FetchStoryMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scraper_FetchChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServer).FetchChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraper.Scraper/FetchChapter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServer).FetchChapter(ctx, req.(*FetchChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scraper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scraper.Scraper",
	HandlerType: (*ScraperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckStoryURL",
			Handler:    _Scraper_CheckStoryURL_Handler,
		},
		{
			MethodName: "FetchStoryMetadata",
			Handler:    _Scraper_FetchStoryMetadata_Handler,
		},
		{
			MethodName: "FetchChapter",
			Handler:    _Scraper_FetchChapter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/scraper/scraper.proto",
}

func init() { proto.RegisterFile("api/scraper/scraper.proto", fileDescriptor_scraper_0a6b167aa046985f) }

var fileDescriptor_scraper_0a6b167aa046985f = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0x75, 0x1f, 0x5d, 0xe7, 0x75, 0x82, 0x5c, 0xab, 0x74, 0xc5, 0x49, 0x89, 0x2f, 0x7d, 0x71,
	0xa2, 0xfe, 0x84, 0x81, 0x20, 0x38, 0x90, 0x8c, 0x3d, 0x4b, 0x6c, 0x03, 0x1d, 0x76, 0x4d, 0x4d,
	0x52, 0xd4, 0x17, 0xff, 0x80, 0x7f, 0x5a, 0x4c, 0x3f, 0x58, 0xdd, 0x2a, 0xf8, 0xd4, 0x9c, 0x93,
	0x73, 0xef, 0xb9, 0xb7, 0x27, 0x30, 0x66, 0xd9, 0xea, 0x4a, 0x85, 0x92, 0x65, 0x5c, 0x56, 0xdf,
	0x69, 0x26, 0x85, 0x16, 0x68, 0x97, 0x90, 0x04, 0xe0, 0xcc, 0x62, 0x1e, 0xbe, 0x2c, 0xb4, 0x90,
	0x1f, 0x4b, 0xfa, 0x40, 0xf9, 0x6b, 0xce, 0x95, 0xc6, 0x23, 0xe8, 0xe5, 0x32, 0x71, 0x3b, 0x7e,
	0x27, 0xd8, 0xa7, 0x3f, 0x47, 0x72, 0x0d, 0x27, 0xbf, 0x94, 0x2a, 0x13, 0xa9, 0xe2, 0xe8, 0x82,
	0xcd, 0x92, 0x44, 0xbc, 0xf1, 0xc8, 0xc8, 0x87, 0xb4, 0x82, 0xe4, 0x12, 0xc6, 0x77, 0x5c, 0x87,
	0xb1, 0x29, 0x99, 0x73, 0xcd, 0x22, 0xa6, 0x59, 0xbb, 0xc3, 0x27, 0x78, 0xbb, 0xe4, 0xa5, 0xcd,
	0x96, 0x1e, 0x1d, 0xb0, 0xf4, 0x4a, 0x27, 0xdc, 0xed, 0x1a, 0xae, 0x00, 0x78, 0x0a, 0x03, 0x96,
	0xeb, 0x58, 0x48, 0xb7, 0x67, 0xe8, 0x12, 0xa1, 0x0f, 0x07, 0x69, 0xbe, 0x9e, 0xc5, 0x2c, 0xd3,
	0x5c, 0x2a, 0xb7, 0xef, 0x77, 0x02, 0x8b, 0x6e, 0x52, 0x64, 0x09, 0xc7, 0xc6, 0xbf, 0x24, 0xaa,
	0x41, 0x3d, 0x18, 0x2a, 0xb3, 0x73, 0xed, 0x5e, 0x63, 0x24, 0x30, 0x0a, 0x0b, 0xf5, 0x7d, 0x1a,
	0xf1, 0x77, 0x33, 0x89, 0x45, 0x1b, 0x1c, 0xa1, 0xe0, 0x34, 0xdb, 0xfe, 0x73, 0x21, 0x84, 0x7e,
	0xac, 0xd7, 0x49, 0xb9, 0x8e, 0x39, 0xdf, 0x7c, 0x75, 0xc1, 0x5e, 0x14, 0x11, 0xe2, 0x23, 0x1c,
	0x36, 0x82, 0xc1, 0xc9, 0xb4, 0x0a, 0x7b, 0x57, 0xb4, 0xde, 0x79, 0xdb, 0x75, 0x31, 0x17, 0xd9,
	0xc3, 0x27, 0xc0, 0xed, 0x20, 0x90, 0xd4, 0x75, 0xad, 0xa1, 0x7a, 0x17, 0x7f, 0x6a, 0x6a, 0x83,
	0x39, 0x8c, 0x36, 0x7f, 0x09, 0x9e, 0x35, 0xcb, 0x9a, 0x01, 0x78, 0x93, 0x96, 0xdb, 0xaa, 0xdd,
	0xf3, 0xc0, 0x3c, 0xea, 0xdb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x29, 0x9f, 0xd8, 0x3a, 0xf1,
	0x02, 0x00, 0x00,
}
