apiVersion: v1
kind: Service
metadata:
  name: reader
  labels:
    app: reader
    tier: frontend
spec:
  selector:
    app: reader
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
      tier: frontend
  template:
    metadata:
      labels:
        app: reader
        tier: frontend
    spec:
      containers:
        - name: reader
          image: gcr.io/arkhaix-lit-reader/reader
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          env:
            - name: REACT_APP_READER_API
              value: "http://reader.arkhaix.com"