apiVersion: v1
kind: Service
metadata:
  name: story-grpc
  labels:
    app: story-grpc
    tier: backend
spec:
  selector:
    app: story-grpc
    tier: backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story-grpc
      tier: backend
  template:
    metadata:
      labels:
        app: story-grpc
        tier: backend
    spec:
      containers:
        - name: story-grpc
          image: gcr.io/arkhaix-lit-reader/story-grpc
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 3000
          env:
            - name: SCRAPER_GRPC_SERVICE_HOSTNAME
              value: "scraper-grpc"
            - name: STORY_DB_STRING
              value: "postgresql://story_service@cockroachdb-public:26257/reader?sslmode=disable"