apiVersion: batch/v1
kind: Job
metadata:
  name: cockroach-init
  labels:
    app: cockroachdb
spec:
  template:
    spec:
      containers:
      - name: cockroach-init
        image: gcr.io/arkhaix-lit-reader/cockroach-init
        imagePullPolicy: Always
        command: ['/cockroach/cr-init.sh']
        env:
        - name: COCKROACH_HOSTNAME
          value: "cockroachdb-public"
      restartPolicy: OnFailure
