apiVersion: v1
kind: Service
metadata:
  name: chapter-http
  labels:
    app: chapter-http
    tier: backend
spec:
  selector:
    app: chapter-http
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chapter-http
  labels:
    app: chapter-http
    tier: backend
spec:
  replicas: 3
  template:
    spec:
      metadata:
        name: chapter-http
        labels:
          app: chapter-http
          tier: backend
      containers:
        - name: chapter-http
          image: gcr.io/arkhaix-lit-reader/chapter-http
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: CHAPTER_GRPC_SERVICE_HOSTNAME
              value: "chapter-grpc"