apiVersion: v1
kind: Service
metadata:
  name: chapter-grpc
  labels:
    app: chapter-grpc
    tier: backend
spec:
  selector:
    app: chapter-grpc
    tier: backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chapter-grpc
  labels:
    app: chapter-grpc
    tier: backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: chapter-grpc
        tier: backend
    spec:
      containers:
        - name: chapter-grpc
          image: gcr.io/arkhaix-lit-reader/chapter-grpc
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 3000
          env:
            - name: SCRAPER_GRPC_SERVICE_HOSTNAME
              value: "scraper-grpc"
            - name: STORY_GRPC_SERVICE_HOSTNAME
              value: "story-grpc"
            - name: CHAPTER_DB_STRING
              value: "postgresql://chapter_service@roach:26257/reader?sslmode=disable"