apiVersion: v1
kind: Service
metadata:
  name: scraper-grpc
  labels:
    name: scraper-grpc
    tier: backend
spec:
  selector:
    app: scraper-grpc
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scraper-grpc
  labels:
    app: scraper-grpc
    tier: backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: scraper-grpc
        tier: backend
    spec:
      containers:
        - name: scraper-grpc
          image: gcr.io/arkhaix-lit-reader/scraper-grpc
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 3000