kind: Service
apiVersion: v1
metadata:
  name: scraper-grpc
  labels:
    app: scraper-grpc
spec:
  selector:
    app: scraper-grpc
    tier: backend
  ports:
  - name: grpc
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-grpc
  labels:
    app: scraper-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-grpc
  template:
    metadata:
      labels:
        app: scraper-grpc
    spec:
      containers:
      - name: scraper-grpc
        # minikube
        image: scraper-grpc
        imagePullPolicy: Never
        # google container engine
        #image: gcr.io/arkhaix-lit-reader/scraper-grpc
        #imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 3000