apiVersion: v1
kind: Service
metadata:
  name: "scraper-grpc"
spec:
  selector:
    app: "scraper-grpc"
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scraper-grpc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: scraper-grpc
    spec:
      containers:
        - name: scraper-grpc
          # minikube
          #image: scraper-grpc
          #imagePullPolicy: Never
          # google container engine
          image: gcr.io/arkhaix-lit-reader/scraper-grpc
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 3000