apiVersion: v1
kind: Service
metadata:
  name: "story-grpc"
spec:
  selector:
    app: "story-grpc"
  ports:
    - protocol: "TCP"
      port: 3001
      targetPort: 3001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: story-grpc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: story-grpc
    spec:
      containers:
        - name: story-grpc
          # minikube
          #image: story-grpc
          #imagePullPolicy: Never
          # google container engine
          image: gcr.io/arkhaix-lit-reader/story-grpc
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 3001
          env:
            - name: SCRAPER_GRPC_SERVICE_HOSTNAME
              value: "scraper-grpc"
            - name: STORY_DB_STRING
              value: "postgresql://maxroach@cockroachdb-public:26257/story?sslmode=disable"