apiVersion: v1
kind: Service
metadata:
  name: story-http
spec:
  selector:
    app: story-http
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: story-http
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: story-http
    spec:
      containers:
        - name: story-http
          # minikube
          #image: story-http
          #imagePullPolicy: Never
          # google container engine
          image: gcr.io/arkhaix-lit-reader/story-http
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: STORY_GRPC_SERVICE_HOSTNAME
              value: "story-grpc"