apiVersion: v1
kind: Service
metadata:
  name: story-http
  labels:
    app: story-http
    tier: backend
spec:
  selector:
    app: story-http
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story-http
      tier: backend
  template:
    metadata:
      labels:
        app: story-http
        tier: backend
    spec:
      containers:
        - name: story-http
          image: gcr.io/arkhaix-lit-reader/story-http
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: STORY_GRPC_SERVICE_HOSTNAME
              value: "story-grpc"