version: '3'
services:
  reader:
    image: reader
    build:
      context: ../../
      dockerfile: ./build/reader.Dockerfile
    ports:
      - "81:80"
    labels:
      - "traefik.frontend.rule=Host:reader.dev.local"
      - "traefik.enable=true"
  story-http:
    image: story-http
    build:
      context: ../../
      dockerfile: ./build/story-http.Dockerfile
    ports:
      - "8081:8080"
    environment:
      - STORY_GRPC_SERVICE_HOSTNAME=story-grpc
      - STORY_GRPC_SERVICE_PORT=3000
      - STORY_HTTP_SERVICE_PORT=8080
    depends_on:
      - story-grpc
    labels:
      - "traefik.frontend.rule=Host:reader.dev.local;PathPrefix:/story"
      - "traefik.enable=true"
  chapter-http:
    image: chapter-http
    build:
      context: ../../
      dockerfile: ./build/chapter-http.Dockerfile
    ports:
      - "8082:8080"
    environment:
      - CHAPTER_GRPC_SERVICE_HOSTNAME=chapter-grpc
      - CHAPTER_GRPC_SERVICE_PORT=3000
      - CHAPTER_HTTP_SERVICE_PORT=8080
    depends_on:
      - chapter-grpc
    labels:
      - "traefik.frontend.rule=Host:reader.dev.local;PathPrefix:/chapter"
      - "traefik.enable=true"
  story-grpc:
    image: story-grpc
    build:
      context: ../../
      dockerfile: ./build/story-grpc.Dockerfile
    environment:
      - SCRAPER_GRPC_SERVICE_HOSTNAME=scraper-grpc
      - SCRAPER_GRPC_SERVICE_PORT=3000
      - STORY_DB_STRING=postgresql://story_service@roach:26257/reader?sslmode=disable
    depends_on:
      - cockroach
      - scraper-grpc
  chapter-grpc:
    image: chapter-grpc
    build:
      context: ../../
      dockerfile: ./build/chapter-grpc.Dockerfile
    environment:
      - SCRAPER_GRPC_SERVICE_HOSTNAME=scraper-grpc
      - SCRAPER_GRPC_SERVICE_PORT=3000
      - STORY_GRPC_SERVICE_HOSTNAME=story-grpc
      - STORY_GRPC_SERVICE_PORT=3000
      - STORY_DB_STRING=postgresql://chapter_service@roach:26257/reader?sslmode=disable
    depends_on:
      - cockroach
      - scraper-grpc
      - story-grpc
  scraper-grpc:
    image: scraper-grpc
    build:
      context: ../../
      dockerfile: ./build/scraper-grpc.Dockerfile
  cockroach:
    image: cockroachdb/cockroach:v2.0.5
    command: start --insecure
    container_name: roach
    ports:
      - "8079:8080"
      - "26257:26257"
    volumes:
      - ./cockroach-data/roach:/cockroach/cockroach-data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    labels:
      - "traefik.backend=cockroach"
      - "traefik.frontend.rule=Host:cockroach.dev.local"
      - "traefik.enable=true"
  cockroach-init:
    image: cockroach-init
    build:
      context: ../../
      dockerfile: ./build/cockroach-init.Dockerfile
    entrypoint: /cockroach/cr-init.sh
    container_name: roach-init
    depends_on:
      - cockroach
    environment:
      - COCKROACH_HOSTNAME=roach
  reverse-proxy:
    image: traefik
    command: --api --docker
    restart: always
    container_name: traefik
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock