version: '2'
services:
  reader:
    image: reader
    build:
      context: ../../
      dockerfile: ./build/reader.Dockerfile
    container_name: reader
    depends_on:
      - elasticsearch
      - story-http
      - chapter-http
  story-http:
    image: story-http
    build:
      context: ../../
      dockerfile: ./build/story-http.Dockerfile
    container_name: story-http
    environment:
      - STORY_GRPC_SERVICE_HOSTNAME=story-grpc
      - STORY_GRPC_SERVICE_PORT=3000
      - STORY_HTTP_SERVICE_PORT=8080
    depends_on:
      - elasticsearch
      - story-grpc
  chapter-http:
    image: chapter-http
    build:
      context: ../../
      dockerfile: ./build/chapter-http.Dockerfile
    container_name: chapter-http
    environment:
      - CHAPTER_GRPC_SERVICE_HOSTNAME=chapter-grpc
      - CHAPTER_GRPC_SERVICE_PORT=3000
      - CHAPTER_HTTP_SERVICE_PORT=8080
    depends_on:
      - elasticsearch
      - chapter-grpc
  story-grpc:
    image: story-grpc
    build:
      context: ../../
      dockerfile: ./build/story-grpc.Dockerfile
    container_name: story-grpc
    environment:
      - SCRAPER_GRPC_SERVICE_HOSTNAME=scraper-grpc
      - SCRAPER_GRPC_SERVICE_PORT=3000
      - STORY_DB_STRING=postgresql://story_service@cockroach:26257/reader?sslmode=disable
    depends_on:
      - elasticsearch
      - cockroach
      - scraper-grpc
  chapter-grpc:
    image: chapter-grpc
    build:
      context: ../../
      dockerfile: ./build/chapter-grpc.Dockerfile
    container_name: chapter-grpc
    environment:
      - SCRAPER_GRPC_SERVICE_HOSTNAME=scraper-grpc
      - SCRAPER_GRPC_SERVICE_PORT=3000
      - STORY_GRPC_SERVICE_HOSTNAME=story-grpc
      - STORY_GRPC_SERVICE_PORT=3000
      - CHAPTER_DB_STRING=postgresql://chapter_service@cockroach:26257/reader?sslmode=disable
    depends_on:
      - elasticsearch
      - cockroach
      - scraper-grpc
      - story-grpc
  scraper-grpc:
    image: scraper-grpc
    build:
      context: ../../
      dockerfile: ./build/scraper-grpc.Dockerfile
    container_name: scraper-grpc
  cockroach:
    image: cockroachdb/cockroach:v2.0.5
    command: start --insecure
    container_name: cockroach
    volumes:
      - ./cockroach-data/cockroach:/cockroach/cockroach-data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  cockroach-init:
    image: cockroach-init
    build:
      context: ../../
      dockerfile: ./build/cockroach-init.Dockerfile
    entrypoint: /cockroach/cr-init.sh
    container_name: cockroach-init
    depends_on:
      - cockroach
    environment:
      - COCKROACH_HOSTNAME=cockroach
  graylog:
    image: graylog/graylog:2.4
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://graylog:9000
      - GRAYLOG_REST_LISTEN_URI=http://0.0.0.0:9000/api
      - GRAYLOG_REST_TRANSPORT_URI=http://graylog:9000/api
      - GRAYLOG_REST_ENABLE_CORS=true
      - GRAYLOG_REST_ENABLE_TLS=false
      - GRAYLOG_WEB_ENABLE=true
      - GRAYLOG_WEB_LISTEN_URI=http://0.0.0.0:9000
      - GRAYLOG_WEB_TRANSPORT_URI=http://graylog:9000
      - GRAYLOG_WEB_ENABLE_CORS=true
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_ELASTICSEARCH_SHARDS=1
      - GRAYLOG_ELASTICSEARCH_REPLICAS=0
    depends_on:
      - mongo
      - elasticsearch
    volumes:
      - graylog:/usr/share/graylog/data/journal
  elasticsearch:
    image: elasticsearch
    build:
      context: ../../
      dockerfile: ./build/elasticsearch.Dockerfile
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  mongo:
    image: mongo:3
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    command: mongod --smallfiles --logpath=/dev/null
  reverse-proxy:
    image: nginx-rproxy
    container_name: nginx-rproxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - reader
      - story-http
      - chapter-http
      - cockroach
volumes:
  esdata:
    driver: local
  mongo:
    driver: local
  graylog:
    driver: local