version: '2'
services:
  reader:
    image: reader
    container_name: reader
    build:
      context: ../../
      dockerfile: ./build/reader.Dockerfile
    depends_on:
      - story-http
      - chapter-http
  story-http:
    image: story-http
    container_name: story-http
    build:
      context: ../../
      dockerfile: ./build/story-http.Dockerfile
    environment:
      - STORY_GRPC_SERVICE_HOSTNAME=story-grpc
      - STORY_GRPC_SERVICE_PORT=3000
      - STORY_HTTP_SERVICE_PORT=8080
    depends_on:
      - story-grpc
  chapter-http:
    image: chapter-http
    container_name: chapter-http
    build:
      context: ../../
      dockerfile: ./build/chapter-http.Dockerfile
    environment:
      - CHAPTER_GRPC_SERVICE_HOSTNAME=chapter-grpc
      - CHAPTER_GRPC_SERVICE_PORT=3000
      - CHAPTER_HTTP_SERVICE_PORT=8080
    depends_on:
      - chapter-grpc
  story-grpc:
    image: story-grpc
    container_name: story-grpc
    build:
      context: ../../
      dockerfile: ./build/story-grpc.Dockerfile
    environment:
      - SCRAPER_GRPC_SERVICE_HOSTNAME=scraper-grpc
      - SCRAPER_GRPC_SERVICE_PORT=3000
      - STORY_DB_STRING=postgresql://story_service@cockroach:26257/reader?sslmode=disable
    depends_on:
      - cockroach
      - scraper-grpc
  chapter-grpc:
    image: chapter-grpc
    container_name: chapter-grpc
    build:
      context: ../../
      dockerfile: ./build/chapter-grpc.Dockerfile
    environment:
      - SCRAPER_GRPC_SERVICE_HOSTNAME=scraper-grpc
      - SCRAPER_GRPC_SERVICE_PORT=3000
      - STORY_GRPC_SERVICE_HOSTNAME=story-grpc
      - STORY_GRPC_SERVICE_PORT=3000
      - CHAPTER_DB_STRING=postgresql://chapter_service@cockroach:26257/reader?sslmode=disable
    depends_on:
      - cockroach
      - scraper-grpc
      - story-grpc
  scraper-grpc:
    image: scraper-grpc
    container_name: scraper-grpc
    build:
      context: ../../
      dockerfile: ./build/scraper-grpc.Dockerfile
  cockroach:
    image: cockroachdb/cockroach:v2.0.5
    container_name: cockroach
    command: start --insecure
    volumes:
      - ./cockroach-data/cockroach:/cockroach/cockroach-data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  cockroach-init:
    image: cockroach-init
    container_name: cockroach-init
    build:
      context: ../../
      dockerfile: ./build/cockroach-init.Dockerfile
    entrypoint: /cockroach/cr-init.sh
    depends_on:
      - cockroach
    environment:
      - COCKROACH_HOSTNAME=cockroach
  prometheus:
    image: prometheus
    container_name: prometheus
    build:
      context: ../../
      dockerfile: ./build/prometheus.Dockerfile
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana
    container_name: grafana
    build:
      context: ../../
      dockerfile: ./build/grafana.Dockerfile
    volumes:
      - grafana-data:/var/lib/grafana
  reverse-proxy:
    image: nginx-rproxy
    container_name: nginx-rproxy
    build:
      context: ../../
      dockerfile: ./build/nginx-rproxy.Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - reader
      - story-http
      - chapter-http
      - cockroach
volumes:
  grafana-data:
    driver: local
