version: '3'
services:
  scraper-grpc:
    build:
      context: ../../
      dockerfile: ./build/servers/grpc/scraper.Dockerfile
    ports:
     - "3000:3000"
  storytest-http:
    build:
      context: ../../
      dockerfile: ./build/servers/http/storytest.Dockerfile
    ports:
     - "8080:8080"
    environment:
     - SCRAPER_GRPC_SERVICE_HOSTNAME=scraper-grpc
     - SCRAPER_GRPC_SERVICE_PORT=3000