version: '3'
services:
  scraper-grpc:
    build:
      context: ../../
      dockerfile: ./build/servers/grpc/scraper.Dockerfile
    ports:
     - "3000:3000"
  story-grpc:
    build:
      context: ../../
      dockerfile: ./build/servers/grpc/story.Dockerfile
    ports:
     - "3001:3001"
    environment:
     - SCRAPER_GRPC_SERVICE_HOSTNAME=scraper-grpc
     - SCRAPER_GRPC_SERVICE_PORT=3000
  story-http:
    build:
      context: ../../
      dockerfile: ./build/servers/http/story.Dockerfile
    ports:
     - "8080:8080"
    environment:
     - STORY_GRPC_SERVICE_HOSTNAME=story-grpc
     - STORY_GRPC_SERVICE_PORT=3001